# Generated by Django 3.0.8 on 2020-07-23 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='webinarsmodel',
        ),
    ]
