# Generated by Django 3.0.8 on 2020-07-25 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0003_webinarsmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webinarsmodel',
            old_name='status',
            new_name='is_completed',
        ),
        migrations.RenameField(
            model_name='webinarsmodel',
            old_name='task_details',
            new_name='webinar_details',
        ),
        migrations.RenameField(
            model_name='webinarsmodel',
            old_name='task_heading',
            new_name='webinar_heading',
        ),
    ]
