# Generated by Django 3.0.8 on 2020-07-25 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0004_auto_20200725_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webinarsmodel',
            old_name='is_completed',
            new_name='status',
        ),
    ]
