# Generated by Django 3.0.7 on 2020-08-02 07:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0005_auto_20200725_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinarsmodel',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webinarsmodel',
            name='webinar_image',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
